# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest2():
  def setup_method(self, method):
    self.driver = webdriver.Chrome() #self.driver = webdriver.Chrome("/home/mihael/Desktop/selenium/chromedriver_linux64/chromedriver")
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test2(self):
    self.driver.get("https://www.hr/")
    time.sleep(1)
    self.driver.set_window_size(1853, 1173)
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, ".cbp-item:nth-child(2) .cbp-l-caption-body").click()
    time.sleep(1)
    self.driver.find_element(By.LINK_TEXT, "Kulen i kulenova seka").click()
  
